version: "3.9"

services:
  ###########################################################################
  # ───────────── INDEXERS ─────────────
  ###########################################################################
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    volumes:
      - ${ARRPATH}Prowlarr/config:/config
      - ${ARRPATH}Prowlarr/backup:/data/Backup
      - ${CACHE}Downloads:/downloads
    ports:
      - "9696:9696"
    restart: unless-stopped
    env_file:
      - ".env"

  ###########################################################################
  # ───────────── TV AUTOMATION ─────────────
  ###########################################################################
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    volumes:
      - ${ARRPATH}Sonarr/config:/config
      - ${ARRPATH}Sonarr/backup:/data/Backup
      - ${NASDRIVE_1}Sonarr/tvshows:/data/nas_tvshows
      - ${NASDRIVE_1}Anime:/data/nas_anime
      - ${CACHE}Downloads:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped
    env_file:
      - ".env"

  ###########################################################################
  # ───────────── MOVIE AUTOMATION ─────────────
  ###########################################################################
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    volumes:
      - ${ARRPATH}Radarr/config:/config
      - ${ARRPATH}Radarr/backup:/data/Backup
      - ${NASDRIVE_1}Radarr/movies:/data/nas_movies
      - ${CACHE}Downloads:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped
    env_file:
      - ".env"

  ###########################################################################
  # ───────────── MUSIC AUTOMATION ─────────────
  ###########################################################################
  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    hostname: lidarr
    volumes:
      - ${ARRPATH}Lidarr/config:/config
      - ${NASDRIVE_1}Lidarr/music:/data/nas_music
      - ${CACHE}Downloads:/downloads
    ports:
      - "8686:8686"
    restart: unless-stopped
    env_file:
      - ".env"

  ###########################################################################
  # ───────────── HOMEPAGE / DASHBOARD ─────────────
  ###########################################################################
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    restart: unless-stopped
    volumes:
      - ${ARRPATH}Homarr/configs:/app/data/configs
      - ${ARRPATH}Homarr/icons:/app/public/icons
      - ${ARRPATH}Homarr/data:/data
    ports:
      - "7575:7575"
    env_file:
      - ".env"

  ###########################################################################
  # ───────────── MEDIA SERVER ─────────────
  ###########################################################################
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    ports:
      - "8096:8096/tcp"
      - "7359:7359/udp"
      - "1900:1900/udp"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    volumes:
      - ${ARRPATH}Jellyfin/config:/config
      - ${NASDRIVE_1}Radarr/movies:/data/nas_Movies
      - ${NASDRIVE_1}Sonarr/tvshows:/data/nas_TVShows
      - ${NASDRIVE_1}Lidarr/music:/data/nas_Music
      - ${NASDRIVE_1}Anime:/data/nas_Anime
    restart: unless-stopped
    env_file:
      - ".env"

  ###########################################################################
  # ───────────── REQUEST MANAGEMENT ─────────────
  ###########################################################################
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    ports:
      - "5055:5055"
    volumes:
      - ${ARRPATH}Jellyseerr/config:/app/config
    restart: unless-stopped
    env_file:
      - ".env"

  ###########################################################################
  # ───────────── TORRENT CLIENT ─────────────
  ###########################################################################
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    hostname: qbittorrent
    volumes:
      - ${ARRPATH}qbittorrent/config:/config
      - ${CACHE}Downloads:/downloads
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    environment:
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: unless-stopped
    env_file:
      - ".env"

  ###########################################################################
  # ───────────── TRANSCODE SERVER ─────────────
  ###########################################################################
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: tdarr
    hostname: tdarr
    ports:
      - "8265:8265"
      - "8266:8266"
    volumes:
      - ${ARRPATH}Tdarr/config:/app/config
      - ${CACHE}Tdarr/cache:/temp
      - ${NASDRIVE_1}Radarr/movies:/data/nas_movies
      - ${NASDRIVE_1}Sonarr/tvshows:/data/nas_tvshows
      - ${NASDRIVE_1}Anime:/data/nas_anime
    restart: unless-stopped
    env_file:
      - ".env"

  ###########################################################################
  # ───────────── TRANSCODE WORKER NODE ─────────────
  ###########################################################################
  tdarr-node:
    image: ghcr.io/haveagitgat/tdarr_node:latest
    container_name: tdarr-node
    hostname: tdarr-node
    depends_on:
      - tdarr
    ports:
      - "8267:8267"
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${ARRPATH}Tdarr/config:/app/config
      - ${CACHE}Tdarr/cache:/temp
      - ${NASDRIVE_1}Radarr/movies:/data/nas_movies
      - ${NASDRIVE_1}Sonarr/tvshows:/data/nas_tvshows
      - ${NASDRIVE_1}Anime:/data/nas_anime
    restart: unless-stopped
    env_file:
      - ".env"
    environment:
      - nodeID=tdarr-node
      - serverIP=tdarr
      - serverPort=8266
      - UMASK_SET=002

      version: "2.1"
      
   ###########################################################################
  # ───────────── Proxy Through CloudFlare ─────────────
  ###########################################################################   
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
